sonar.projectKey=elainedb_ytdash_rn_gemini
sonar.organization=elainedb

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=ytdash_rn_gemini
sonar.projectVersion=1.0

# Source code paths
sonar.sources=app,components,hooks,ils,constants

# Test paths
sonar.tests=.
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# Exclusions from analysis
sonar.exclusions=node_modules/**,coverage/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,jest.config.js,babel.config.js

# Coverage paths
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Language settings
sonar.typescript.node=18

# Encoding of the source code
sonar.sourceEncoding=UTF-8